services:
  mongo:
    build:
      context: ./database
      dockerfile: mongo.Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./database/data_v:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: local
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/
      SPRING_PROFILES_ACTIVE: local

    depends_on:
      - mongo
